services:
  traefik:
    image: traefik:v3.0
    command:
      # dashboard
      - "--api.dashboard=true"
      - "--api.insecure=false"
      # providers
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      # entrypoints
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls.certresolver=myresolver"
      # certificates resolvers
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=${EMAIL}"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"

# labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.${APP_DOMAIN}.rule=Host(`${APP_DOMAIN}`)"
#      - "traefik.http.routers.${APP_DOMAIN}.entrypoints=websecure"
#      - "traefik.http.routers.${APP_DOMAIN}.tls.certresolver=myresolver"
#      - "traefik.http.services.${APP_DOMAIN}.loadbalancer.server.port=3000"
